/**
 * Catálogo oficial de MongoDB para el POS y ShipFast.
 * Fuente de verdad de /interno — actualizar aquí al cambiar modelos.
 */

/** Campos automáticos que comparten casi todas las colecciones. */
export const MONGO_TIMESTAMP_FIELDS = [
  {
    name: "createdAt",
    type: "Date",
    key: "Cuándo se creó el documento (Mongoose timestamps).",
  },
  {
    name: "updatedAt",
    type: "Date",
    key: "Cuándo se modificó por última vez (Mongoose timestamps).",
  },
];

/** Convenciones globales mostradas en /interno. */
export const MONGO_GLOBAL_CONVENTIONS = [
  {
    id: "timestamps",
    title: "Fechas automáticas (createdAt / updatedAt)",
    summary:
      "Todas las colecciones usan { timestamps: true } en Mongoose. No hace falta enviarlas desde el frontend.",
    appliesTo: "Las 26 colecciones documentadas abajo.",
    fields: MONGO_TIMESTAMP_FIELDS,
  },
  {
    id: "business-keys",
    title: "Claves de negocio (no ObjectId)",
    summary:
      "El _id de Mongo existe, pero la app enlaza tablas con códigos legibles en String (ej. staffCode «CA», clientCode «SA-4092»).",
    appliesTo:
      "appointmentCode, staffCode, clientCode, paymentCode, sessionCode, settlementCode, activityCode, etc.",
    fields: [
      {
        name: "Código único por colección",
        type: "String",
        key: "PK lógica de la app. Índice unique en Mongoose.",
      },
      {
        name: "FK como String",
        type: "String",
        key: "Ej. PosAppointment.staffId guarda PosStaff.staffCode — no es ObjectId.",
      },
    ],
  },
  {
    id: "sensitive-fields",
    title: "Campos sensibles en /interno",
    summary:
      "PINs y claves master se enmascaran (••••) en las muestras del panel. Están en Mongo pero no se muestran en claro.",
    appliesTo: "loginCode, masterLoginCode y campos marcados sensitive en el catálogo.",
    fields: [
      {
        name: "loginCode",
        type: "String",
        key: "PIN de 4 dígitos — recepción, manicurista, contadora.",
        sensitive: true,
      },
      {
        name: "masterLoginCode",
        type: "String",
        key: "PIN master de respaldo (PosScheduleConfig).",
        sensitive: true,
      },
    ],
  },
  {
    id: "snapshots",
    title: "Snapshots congelados (auditoría)",
    summary:
      "Al liquidar o descargar reporte se guarda una copia de los datos en ese momento. Si luego cambia una cita, el histórico no se altera.",
    appliesTo: "PosStaffSettlement.appointmentSnapshots[], PosAccountantActivity.reportSnapshot[]",
    fields: [
      {
        name: "appointmentSnapshots[]",
        type: "Array",
        key: "Cita congelada: appointmentCode, date, time, clientName, serviceName, cost, commissionAmount, status.",
      },
      {
        name: "reportSnapshot[]",
        type: "Array",
        key: "Misma estructura — respaldo del reporte sin guardar PDF en Mongo.",
      },
    ],
  },
];

const TS = MONGO_TIMESTAMP_FIELDS;

function withTimestamps(fields) {
  return [...fields, ...TS];
}

export const MONGO_RELATIONSHIPS = [
  // ── Clientes y agenda ──
  {
    from: "PosClient",
    field: "clientCode",
    to: "PosAppointment",
    targetField: "clientId",
    description: "Cada cita pertenece a una clienta por su código (ej. SA-4092).",
  },
  {
    from: "PosStaff",
    field: "staffCode",
    to: "PosAppointment",
    targetField: "staffId",
    description: "Manicurista asignada a la cita (columna en agenda).",
  },
  {
    from: "PosStaff",
    field: "staffCode",
    to: "PosBlockedSlot",
    targetField: "staffId",
    description: "Bloqueos de horario (descanso, comida) por manicurista.",
  },
  {
    from: "PosReceptionist",
    field: "receptionistCode",
    to: "PosAppointment",
    targetField: "bookedByReceptionistId",
    description: "Quién agendó la cita desde recepción.",
  },
  {
    from: "PosAppointment",
    field: "bookedByReceptionistId + bookedOnDate",
    to: "PosReceptionist",
    targetField: "bookingsToday / bookingsTodayDate",
    description:
      "Al crear una cita se incrementa el contador diario de la recepcionista que la agendó.",
  },
  {
    from: "PosDailySnapshot",
    field: "date",
    to: "PosAppointment",
    targetField: "date",
    description: "Contadores del día (citas, pagadas, canceladas) por fecha de cita.",
  },
  {
    from: "PosWeeklySnapshot",
    field: "weekStartDate",
    to: "PosAppointment",
    targetField: "date (sáb–vie)",
    description:
      "KPI semanal agrega citas terminadas de la semana operativa (sábado a viernes).",
  },
  {
    from: "PosWeeklySnapshot",
    field: "weekStartDate",
    to: "PosPayment",
    targetField: "appointmentDate (sáb–vie)",
    description: "Propinas y cobros de la semana alimentan grossSales, tips y salonNet.",
  },
  {
    from: "PosWeeklySnapshot",
    field: "weekStartDate",
    to: "PosCashSession",
    targetField: "shiftDate (sáb–vie, status closed)",
    description: "Cortes cerrados de la semana alimentan cutsCount, cutsTotal y desgloses.",
  },
  {
    from: "PosWeeklySnapshot",
    field: "weekStartDate",
    to: "PosStaff",
    targetField: "staffCode vía salesByStaff / completedByStaff",
    description: "Desglose semanal por manicurista usa commissionPercent de PosStaff.",
  },
  // ── CRM ──
  {
    from: "PosAppointment",
    field: "clientId + date + status",
    to: "PosClient",
    targetField: "crmSegmentFlags / crmSegmentDetails",
    description:
      "Al crear, editar o cancelar citas se recalculan los 7 segmentos CRM en la clienta.",
  },
  {
    from: "PosClient",
    field: "birthday / alerts / registeredAt / lastPaidVisitDate",
    to: "PosClient",
    targetField: "crmSegmentFlags / crmSegmentDetails",
    description:
      "Datos de perfil alimentan segmentos: inactivas, cumpleaños, alertas, nuevas, reagendar, etc.",
  },
  // ── Caja y cobros ──
  {
    from: "PosAppointment",
    field: "appointmentCode",
    to: "PosPayment",
    targetField: "appointmentCode",
    description: "Un cobro por cita; al cobrar en caja la cita pasa a estado «terminado».",
  },
  {
    from: "PosPayment",
    field: "clientId",
    to: "PosClient",
    targetField: "clientCode",
    description: "Clienta que realizó el pago (copia desnormalizada para reportes).",
  },
  {
    from: "PosPayment",
    field: "staffId",
    to: "PosStaff",
    targetField: "staffCode",
    description: "Manicurista del servicio cobrado.",
  },
  {
    from: "PosPayment",
    field: "processedByReceptionistId",
    to: "PosReceptionist",
    targetField: "receptionistCode",
    description: "Recepcionista que procesó el cobro en caja.",
  },
  {
    from: "PosPayment",
    field: "appointmentCode",
    to: "PosClient",
    targetField: "lastPaidVisitDate + crmSegmentFlags",
    description: "Al cobrar se actualiza la última visita pagada y se sincronizan segmentos CRM.",
  },
  {
    from: "PosCashSession",
    field: "sessionCode",
    to: "PosPayment",
    targetField: "cashSessionCode",
    description: "Todos los pagos de un turno apuntan al mismo turno de caja abierto.",
  },
  {
    from: "PosReceptionist",
    field: "receptionistCode",
    to: "PosCashSession",
    targetField: "openedByReceptionistId / closedByReceptionistId",
    description: "Quién abrió y quién cerró el turno de caja.",
  },
  {
    from: "PosCashSession",
    field: "sessionCode",
    to: "PosLoginAudit",
    targetField: "cashSessionCode",
    description: "Auditoría de apertura y cierre de caja enlazada al turno.",
  },
  {
    from: "PosAppointment",
    field: "appointmentCode",
    to: "PosCashTicket",
    targetField: "appointmentCode",
    description: "Ticket de caja enviado por manicurista antes del cobro (Por cobrar).",
  },
  {
    from: "PosCashTicket",
    field: "ticketCode",
    to: "PosPayment",
    targetField: "ticketCode",
    description: "Al cobrar, el ticket pasa a charged y enlaza al pago.",
  },
  {
    from: "PosCashTicket",
    field: "submittedByStaffId",
    to: "PosStaff",
    targetField: "staffCode",
    description: "Manicurista que envió el ticket a caja.",
  },
  {
    from: "PosPayment",
    field: "giftCardCode",
    to: "PosGiftCard",
    targetField: "giftCardCode",
    description: "Venta o redención de gift card vinculada al cobro.",
  },
  {
    from: "PosGiftCard",
    field: "paymentCode",
    to: "PosPayment",
    targetField: "paymentCode",
    description: "Cada gift card vendida tiene su cobro en caja.",
  },
  {
    from: "PosGiftCard",
    field: "cashSessionCode",
    to: "PosCashSession",
    targetField: "sessionCode",
    description: "Turno donde se vendió la gift card.",
  },
  {
    from: "PosService",
    field: "serviceCode",
    to: "PosStaff",
    targetField: "allowedServiceIds[]",
    description: "Servicios del catálogo que cada manicurista puede realizar.",
  },
  {
    from: "PosInventoryCategory",
    field: "categoryCode",
    to: "PosInventoryItem",
    targetField: "categoryCode",
    description: "Categoría del ítem de inventario.",
  },
  // ── Login y auditoría ──
  {
    from: "PosScheduleConfig",
    field: "masterLoginCode",
    to: "PosLoginAudit",
    targetField: "isMaster: true",
    description:
      "PIN master aceptado en recepción, manicurista y contadora; queda marcado isMaster en auditoría.",
  },
  {
    from: "PosReceptionist",
    field: "loginCode (validación)",
    to: "PosLoginAudit",
    targetField: "userId + role: reception",
    description: "Cada intento de login de recepción (éxito o fallo).",
  },
  {
    from: "PosStaff",
    field: "loginCode (validación)",
    to: "PosLoginAudit",
    targetField: "userId + role: manicurista",
    description: "Cada intento de login de manicurista (éxito o fallo).",
  },
  {
    from: "PosAccountant",
    field: "loginCode (validación)",
    to: "PosLoginAudit",
    targetField: "userId + role: accountant",
    description: "Cada intento de login de contadora (éxito o fallo).",
  },
  {
    from: "PosScheduleConfig",
    field: "configCode (default)",
    to: "—",
    targetField: "global",
    description: "Horario del salón, slots, razones de bloqueo y clave master (singleton).",
  },
  // ── Contabilidad y liquidaciones ──
  {
    from: "PosAccountant",
    field: "accountantCode",
    to: "PosStaffSettlement",
    targetField: "accountantId",
    description: "Contadora que autorizó y registró la liquidación de comisión.",
  },
  {
    from: "PosAccountant",
    field: "accountantCode",
    to: "PosAccountantActivity",
    targetField: "accountantId",
    description: "Bitácora: login, logout, reporte descargado, liquidación.",
  },
  {
    from: "PosStaff",
    field: "staffCode",
    to: "PosStaffSettlement",
    targetField: "staffId",
    description: "Manicurista que recibe el pago de comisión del periodo.",
  },
  {
    from: "PosStaffSettlement",
    field: "appointmentCodes[]",
    to: "PosAppointment",
    targetField: "appointmentCode",
    description: "Lista de citas terminadas incluidas en la liquidación.",
  },
  {
    from: "PosStaffSettlement",
    field: "appointmentSnapshots[]",
    to: "PosAppointment",
    targetField: "snapshot congelado",
    description: "Copia de cada cita al momento de liquidar (no cambia si editan la cita después).",
  },
  {
    from: "PosStaffSettlement",
    field: "paymentCodes[]",
    to: "PosPayment",
    targetField: "paymentCode",
    description: "Cobros de caja de las citas liquidadas.",
  },
  {
    from: "PosStaffSettlement",
    field: "cashSessionCodes[]",
    to: "PosCashSession",
    targetField: "sessionCode",
    description: "Turnos de caja donde se cobraron esas citas.",
  },
  {
    from: "PosStaffSettlement",
    field: "loginAuditId",
    to: "PosLoginAudit",
    targetField: "_id",
    description: "Registro de auditoría al confirmar la liquidación.",
  },
  {
    from: "PosPayment",
    field: "appointmentCode",
    to: "PosStaffSettlement",
    targetField: "appointmentCodes[]",
    description: "Una cita cobrada puede aparecer en la liquidación de comisión de su manicurista.",
  },
  {
    from: "PosAccountantActivity",
    field: "settlementCode",
    to: "PosStaffSettlement",
    targetField: "settlementCode",
    description: "Movimiento de bitácora enlazado a un registro de liquidación.",
  },
  {
    from: "PosAccountantActivity",
    field: "appointmentCodes[]",
    to: "PosAppointment",
    targetField: "appointmentCode",
    description: "Citas del periodo en reportes descargados o liquidaciones.",
  },
  {
    from: "PosAccountantActivity",
    field: "paymentCodes[]",
    to: "PosPayment",
    targetField: "paymentCode",
    description: "Cobros referenciados en reporte o liquidación.",
  },
  {
    from: "PosAccountantActivity",
    field: "cashSessionCodes[]",
    to: "PosCashSession",
    targetField: "sessionCode",
    description: "Turnos de caja referenciados en reporte o liquidación.",
  },
  {
    from: "PosAccountantActivity",
    field: "reportSnapshot[]",
    to: "—",
    targetField: "snapshot local",
    description: "Filas del reporte guardadas en Mongo (el PDF solo existe en el navegador).",
  },
  {
    from: "PosAccountantActivity",
    field: "loginAuditId",
    to: "PosLoginAudit",
    targetField: "_id",
    description: "Login/logout enlazado a auditoría (incluye sesión con clave master).",
  },
];

/** Lógica en app que NO persiste en Mongo — documentar aquí al agregar features. */
export const MONGO_DERIVED_FEATURES = [
  {
    id: "cash-close-draft",
    name: "Borrador de corte de caja",
    sourceCollections: ["PosCashSession"],
    storage: "sessionStorage del navegador (no Mongo)",
    segments: ["closingCountedCash", "closingCountedCard", "closingCountedTransfer", "closingNotes"],
    updatesOnMongoChange:
      "Solo aplica al turno abierto; no se guarda en base hasta confirmar cierre.",
  },
  {
    id: "staff-report-pdf",
    name: "PDF / impresión de reporte de manicurista",
    sourceCollections: ["PosAppointment", "PosStaff", "PosAccountantActivity"],
    storage:
      "HTML en navegador (impresión/PDF local); respaldo en Mongo vía reportSnapshot + reportCode",
    segments: [
      "reportCode en PosAccountantActivity",
      "reportSnapshot[] con appointmentCode, fecha, cliente, servicio, costo, comisión",
      "appointmentCodes / paymentCodes / cashSessionCodes",
    ],
    updatesOnMongoChange:
      "Al descargar reporte con sesión contadora, POST /api/pos/accountant-activities persiste snapshot y FKs.",
  },
  {
    id: "settlement-source-data",
    name: "Resolución de citas y cobros al liquidar",
    sourceCollections: [
      "PosAppointment",
      "PosPayment",
      "PosCashSession",
      "PosStaffSettlement",
    ],
    storage: "libs/posSettlementSourceData.js → PosStaffSettlement al crear liquidación",
    segments: [
      "appointmentSnapshots[] congelado en liquidación",
      "appointmentCodes / paymentCodes / cashSessionCodes",
    ],
    updatesOnMongoChange:
      "createStaffSettlement recalcula desde citas terminadas; no se actualiza si luego cambian citas.",
  },
  {
    id: "accountant-logout-beacon",
    name: "Logout contadora al cerrar pestaña",
    sourceCollections: ["PosAccountantActivity"],
    storage: "navigator.sendBeacon → POST /api/pos/accountant-activities",
    segments: ["logoutReason: manual | browser_close"],
    updatesOnMongoChange:
      "Logout manual marca bandera en sessionStorage para evitar duplicado con pagehide.",
  },
  {
    id: "weekly-kpi-snapshot",
    name: "KPIs semanales del dashboard",
    sourceCollections: [
      "PosAppointment",
      "PosPayment",
      "PosCashSession",
      "PosStaff",
      "PosWeeklySnapshot",
    ],
    storage: "PosWeeklySnapshot (posweeklysnapshots) — persistido en Mongo",
    segments: [
      "grossSales / estimatedCommission / tips / salonNet",
      "completedAppointmentsCount / cutsCount / cutsTotal",
      "salesByDay / salesByStaff / cutsByTurn / cutsByReceptionist",
    ],
    updatesOnMongoChange:
      "libs/posWeeklyStats.js recalcula al crear/editar citas, cobrar y cerrar caja. GET /api/pos/weekly-stats.",
  },
];

export const MONGO_COLLECTIONS = [
  {
    model: "PosClient",
    collection: "posclients",
    domain: "POS Salón",
    purpose: "Clientas del estudio: perfil, gasto, visitas y segmentos CRM persistidos.",
    fields: withTimestamps([
      { name: "clientCode", type: "String", key: "PK lógica — código único de clienta.", example: "SA-4092" },
      { name: "name", type: "String", key: "Nombre completo mostrado en agenda y CRM." },
      { name: "email", type: "String", key: "Correo de contacto." },
      { name: "phone", type: "String", key: "Teléfono de contacto." },
      { name: "birthday", type: "String", key: "Fecha de cumpleaños legible — segmento CRM «cumpleaños»." },
      { name: "address", type: "String", key: "Dirección de la clienta." },
      { name: "isPlatinum", type: "Boolean", key: "Legacy — clienta VIP (poco usado)." },
      { name: "memberSince", type: "String", key: "Texto legible «miembro desde» en perfil." },
      { name: "bio", type: "String", key: "Biografía corta en ficha de clienta." },
      { name: "styleProfile.bio", type: "String", key: "Bio dentro del objeto styleProfile." },
      { name: "styleProfile.tags", type: "[String]", key: "Etiquetas de estilo preferido." },
      { name: "alerts", type: "[String]", key: "Alertas manuales — segmento CRM «alertas»." },
      { name: "totalSpent", type: "Number", key: "Gasto acumulado — se actualiza al cobrar." },
      { name: "visitsCount", type: "Number", key: "Número de visitas pagadas." },
      { name: "averageTicket", type: "Number", key: "Ticket promedio (totalSpent / visitsCount)." },
      { name: "registeredAt", type: "Date", key: "Fecha real de registro — segmento CRM «nuevas» (3 sem)." },
      { name: "lastPaidVisitDate", type: "String", key: "Última cita pagada — segmento «reagendar» (3 sem)." },
      { name: "phoneNormalized", type: "String", key: "Teléfono sin formato — índice único anti-duplicados.", sensitive: true },
      { name: "emailNormalized", type: "String", key: "Email en minúsculas — índice único anti-duplicados.", sensitive: true },
      { name: "crmSegmentFlags.inactive", type: "Boolean", key: "Segmento: sin visita reciente." },
      { name: "crmSegmentFlags.upcoming", type: "Boolean", key: "Segmento: tiene cita próxima." },
      { name: "crmSegmentFlags.unconfirmed", type: "Boolean", key: "Segmento: cita sin confirmar." },
      { name: "crmSegmentFlags.nuevas", type: "Boolean", key: "Segmento: clienta nueva (≤3 semanas)." },
      { name: "crmSegmentFlags.birthday", type: "Boolean", key: "Segmento: cumpleaños cercano." },
      { name: "crmSegmentFlags.alerts", type: "Boolean", key: "Segmento: tiene alertas activas." },
      { name: "crmSegmentFlags.reschedule", type: "Boolean", key: "Segmento: conviene reagendar." },
      { name: "crmSegmentDetails", type: "Mixed", key: "Texto explicativo por segmento activo." },
      { name: "crmSegmentsSyncedAt", type: "Date", key: "Última vez que se recalcularon segmentos CRM." },
    ]),
    usedBy: ["Agenda", "Perfil clienta", "Reservas", "Caja", "CRM segmentos"],
  },
  {
    model: "PosStaff",
    collection: "posstaffs",
    domain: "POS Salón",
    purpose: "Manicuristas: perfil, turno, comisión, colores de agenda y PIN de login.",
    fields: withTimestamps([
      { name: "staffCode", type: "String", key: "PK lógica — iniciales únicas.", example: "CA" },
      { name: "name", type: "String", key: "Nombre visible en agenda y equipo." },
      { name: "email", type: "String", key: "Correo de contacto." },
      { name: "phone", type: "String", key: "Teléfono de contacto." },
      { name: "role", type: "String", key: "Título del puesto (ej. Nail Artist)." },
      { name: "status", type: "enum", key: "Estado en vivo: online | offline | break." },
      { name: "rating", type: "Number", key: "Calificación mostrada en perfil (ej. 4.9)." },
      { name: "specialty", type: "String", key: "Especialidad técnica (gel, nail art, etc.)." },
      { name: "shift", type: "String", key: "Turno asignado (ej. Matutino, Completo)." },
      { name: "completedToday", type: "Number", key: "Citas completadas hoy (métrica UI)." },
      { name: "totalToday", type: "Number", key: "Ingresos del día (métrica UI)." },
      { name: "weeklyRevenue", type: "Number", key: "Ingresos de la semana (métrica UI)." },
      { name: "commissionPercent", type: "Number", key: "% de comisión sobre citas terminadas (default 40)." },
      { name: "bio", type: "String", key: "Biografía en perfil de manicurista." },
      { name: "image", type: "String", key: "Ruta de foto en public/staff/." },
      { name: "color", type: "String", key: "Color principal en columna de agenda." },
      { name: "colorLight", type: "String", key: "Variante clara del color de agenda." },
      { name: "allowedServiceIds", type: "[String]", key: "IDs de servicios que puede realizar." },
      { name: "loginCode", type: "String", key: "PIN de 4 dígitos para login manicurista.", sensitive: true },
      { name: "isActive", type: "Boolean", key: "false = dada de baja (soft delete)." },
      { name: "deactivatedAt", type: "Date", key: "Cuándo se dio de baja." },
      {
        name: "deactivatedAgendaDate",
        type: "String",
        key: "Último día visible en agenda tras la baja (inclusive).",
      },
    ]),
    usedBy: ["Agenda", "Login manicurista", "Bloqueos", "Citas", "Liquidaciones", "Equipo"],
  },
  {
    model: "PosReceptionist",
    collection: "posreceptionists",
    domain: "POS Salón",
    purpose: "Recepcionistas: PIN individual, reservas del día y apertura de caja.",
    fields: withTimestamps([
      { name: "receptionistCode", type: "String", key: "PK lógica — código único.", example: "RC" },
      { name: "name", type: "String", key: "Nombre en login y caja." },
      { name: "role", type: "String", key: "Rol mostrado (default «Recepción»)." },
      { name: "loginCode", type: "String", key: "PIN de 4 dígitos para login recepción.", sensitive: true },
      { name: "bookingsToday", type: "Number", key: "Citas agendadas hoy por esta recepcionista." },
      { name: "bookingsTodayDate", type: "String", key: "Fecha del contador bookingsToday." },
      { name: "image", type: "String", key: "URL o ruta de avatar." },
      { name: "color", type: "String", key: "Color en tarjeta de equipo." },
      { name: "colorLight", type: "String", key: "Variante clara del color." },
    ]),
    usedBy: ["Login recepción", "Reservas", "Caja", "Auditoría", "Contador citas del día"],
  },
  {
    model: "PosService",
    collection: "posservices",
    domain: "POS Salón",
    purpose: "Catálogo de servicios del salón: precio, duración y manicuristas habilitadas.",
    fields: withTimestamps([
      { name: "serviceCode", type: "String", key: "PK lógica — ID del servicio.", example: "PL-GEL-EN-MANOS" },
      { name: "name", type: "String", key: "Nombre del servicio en UI." },
      { name: "category", type: "String", key: "Categoría (Uñas, Manos y pies, etc.)." },
      { name: "subtitle", type: "String", key: "Subtítulo corto." },
      { name: "price", type: "Number", key: "Precio base en MXN (unitario si pricingMode=per_nail)." },
      { name: "duration", type: "Number", key: "Duración en minutos." },
      { name: "image", type: "String", key: "Ruta de imagen del servicio." },
      { name: "description", type: "String", key: "Descripción larga." },
      { name: "staffIds", type: "[String]", key: "FK → PosStaff.staffCode — quién puede hacerlo." },
      { name: "exclusive", type: "Boolean", key: "true = solo staffIds listados." },
      { name: "isActive", type: "Boolean", key: "false = oculto en reservas." },
      { name: "pricingMode", type: "enum", key: "fixed | per_nail — precio cerrado o por uña." },
      { name: "nailMax", type: "Number", key: "Tope de multiplicador (10 manos / 20 manos+pies)." },
      { name: "sortOrder", type: "Number", key: "Orden UI: lista oficial 1..N, legacy ≥1000." },
      { name: "source", type: "enum", key: "price_list | legacy — origen del servicio." },
    ]),
    usedBy: ["Reservas", "Catálogo servicios", "Lista de precios (admin)", "Enviar a caja", "PosStaff.allowedServiceIds"],
  },
  {
    model: "PosAppointment",
    collection: "posappointments",
    domain: "POS Salón",
    purpose: "Citas: servicio, horario, costo, estado y vínculos a clienta, staff y recepción.",
    fields: withTimestamps([
      { name: "appointmentCode", type: "String", key: "PK lógica — código único de cita.", example: "APT-…" },
      { name: "date", type: "String", key: "Fecha legible en zona MX (ej. «5 Jul, 2026»)." },
      { name: "time", type: "String", key: "Hora de la cita (ej. «10:30 AM»)." },
      { name: "serviceName", type: "String", key: "Nombre del servicio (puede unir varios con «+»)." },
      { name: "serviceSubtitle", type: "String", key: "Subtítulo o detalle del servicio." },
      { name: "serviceImage", type: "String", key: "Imagen del servicio en UI." },
      { name: "clientId", type: "String", key: "FK → PosClient.clientCode" },
      { name: "clientName", type: "String", key: "Nombre de clienta (copia para listados)." },
      { name: "staffId", type: "String", key: "FK → PosStaff.staffCode" },
      { name: "staffName", type: "String", key: "Nombre de manicurista (copia)." },
      { name: "staffInitials", type: "String", key: "Iniciales para celdas compactas." },
      { name: "cost", type: "Number", key: "Precio del servicio en MXN." },
      { name: "duration", type: "Number", key: "Duración en minutos." },
      {
        name: "status",
        type: "enum",
        key: "agendado | confirmado | terminado | cancelled | pagado | pending | completed",
      },
      { name: "bookedByReceptionistId", type: "String", key: "FK → PosReceptionist.receptionistCode" },
      { name: "bookedByReceptionistName", type: "String", key: "Nombre de quien agendó." },
      { name: "bookedOnDate", type: "String", key: "Día en que se creó la cita — contador recepción." },
    ]),
    usedBy: ["Agenda", "Caja", "Estadísticas diarias", "CRM", "Liquidaciones", "Reportes"],
  },
  {
    model: "PosBlockedSlot",
    collection: "posblockedslots",
    domain: "POS Salón",
    purpose: "Horarios bloqueados por manicurista (descanso, comida, capacitación).",
    fields: withTimestamps([
      { name: "blockedSlotCode", type: "String", key: "PK lógica — código único del bloqueo." },
      { name: "date", type: "String", key: "Fecha del bloqueo (mismo formato que citas)." },
      { name: "staffId", type: "String", key: "FK → PosStaff.staffCode" },
      { name: "time", type: "String", key: "Hora de inicio del bloqueo." },
      { name: "duration", type: "Number", key: "Duración en minutos." },
      { name: "reason", type: "String", key: "Motivo (Descanso, Comida, etc.)." },
    ]),
    usedBy: ["Agenda — columnas manicurista"],
  },
  {
    model: "PosPayment",
    collection: "pospayments",
    domain: "POS Salón",
    purpose: "Cobros en caja: monto, método, propina y enlaces a cita, turno y recepción.",
    fields: withTimestamps([
      { name: "paymentCode", type: "String", key: "PK lógica — código único del cobro." },
      { name: "transactionType", type: "enum", key: "appointment | gift_card_sale" },
      { name: "giftCardCode", type: "String", key: "FK → PosGiftCard.giftCardCode (venta o redención)." },
      { name: "appointmentCode", type: "String", key: "FK → PosAppointment.appointmentCode" },
      { name: "appointmentDate", type: "String", key: "Fecha de la cita (filtro por día)." },
      { name: "clientId", type: "String", key: "FK → PosClient.clientCode" },
      { name: "clientName", type: "String", key: "Nombre de clienta al cobrar." },
      { name: "staffId", type: "String", key: "FK → PosStaff.staffCode" },
      { name: "staffName", type: "String", key: "Nombre de manicurista del servicio." },
      { name: "ticketCode", type: "String", key: "FK → PosCashTicket.ticketCode" },
      { name: "serviceName", type: "String", key: "Servicio cobrado." },
      { name: "serviceLines", type: "Array", key: "Líneas de servicio con name y price." },
      { name: "amount", type: "Number", key: "Monto del servicio sin propina." },
      { name: "tip", type: "Number", key: "Propina." },
      { name: "total", type: "Number", key: "amount + tip." },
      { name: "method", type: "enum", key: "efectivo | tarjeta | transferencia | gift_card | mixto" },
      { name: "cashAmount", type: "Number", key: "Parte en efectivo (si mixto)." },
      { name: "cardAmount", type: "Number", key: "Parte en tarjeta (si mixto)." },
      { name: "transferAmount", type: "Number", key: "Parte en transferencia (si mixto)." },
      { name: "giftCardAmount", type: "Number", key: "Parte cobrada con gift card." },
      { name: "cashSessionCode", type: "String", key: "FK → PosCashSession.sessionCode" },
      { name: "processedByReceptionistId", type: "String", key: "FK → PosReceptionist.receptionistCode" },
      { name: "processedByReceptionistName", type: "String", key: "Nombre de quien cobró." },
      { name: "notes", type: "String", key: "Notas opcionales del cobro." },
    ]),
    usedBy: ["Caja", "Totales de turno", "Historial cortes", "Liquidaciones", "CRM", "Gift cards"],
  },
  {
    model: "PosCashTicket",
    collection: "poscashtickets",
    domain: "POS Salón",
    purpose: "Tickets enviados a caja por manicurista (tablero Por cobrar) antes del cobro.",
    fields: withTimestamps([
      { name: "ticketCode", type: "String", key: "PK lógica — código del ticket.", example: "TKT-…" },
      { name: "appointmentCode", type: "String", key: "FK → PosAppointment.appointmentCode" },
      { name: "appointmentDate", type: "String", key: "Fecha operativa de la cita." },
      { name: "clientId", type: "String", key: "FK → PosClient.clientCode" },
      { name: "clientName", type: "String", key: "Nombre de clienta." },
      { name: "staffId", type: "String", key: "FK → PosStaff.staffCode" },
      { name: "staffName", type: "String", key: "Nombre de manicurista." },
      { name: "lines", type: "Array", key: "Líneas de servicio: name, price, serviceId." },
      { name: "subtotal", type: "Number", key: "Suma de líneas antes de propina." },
      { name: "status", type: "enum", key: "submitted | charged | cancelled" },
      { name: "submittedByStaffId", type: "String", key: "FK → PosStaff.staffCode" },
      { name: "submittedByStaffName", type: "String", key: "Nombre de quien envió a caja." },
      { name: "submittedAt", type: "Date", key: "Cuándo se envió el ticket." },
      { name: "chargedAt", type: "Date", key: "Cuándo se cobró en caja." },
      { name: "paymentCode", type: "String", key: "FK → PosPayment.paymentCode al cobrar." },
      { name: "workPhotos", type: "[String]", key: "URLs de fotos del trabajo (opcional)." },
    ]),
    usedBy: ["Dashboard Por cobrar", "Caja", "Flujo manicurista → recepción"],
  },
  {
    model: "PosGiftCard",
    collection: "posgiftcards",
    domain: "POS Salón",
    purpose: "Gift cards vendidas en caja: saldo, estado y vínculo al cobro.",
    fields: withTimestamps([
      { name: "giftCardCode", type: "String", key: "PK lógica — código único de tarjeta.", example: "GC-…" },
      { name: "initialValue", type: "Number", key: "Monto original al vender." },
      { name: "balance", type: "Number", key: "Saldo disponible." },
      { name: "status", type: "enum", key: "active | redeemed | cancelled" },
      { name: "soldDate", type: "String", key: "Fecha operativa de venta." },
      { name: "soldAt", type: "Date", key: "Timestamp de venta." },
      { name: "paymentCode", type: "String", key: "FK → PosPayment.paymentCode" },
      { name: "cashSessionCode", type: "String", key: "FK → PosCashSession.sessionCode" },
      { name: "purchaseMethod", type: "enum", key: "efectivo | tarjeta | transferencia | mixto" },
      { name: "soldByReceptionistId", type: "String", key: "FK → PosReceptionist.receptionistCode" },
      { name: "soldByReceptionistName", type: "String", key: "Nombre de quien vendió." },
      { name: "notes", type: "String", key: "Notas opcionales." },
      { name: "redeemedAt", type: "Date", key: "Cuándo se agotó el saldo." },
    ]),
    usedBy: ["Caja — venta directa", "Cobros con gift card", "Totales de turno"],
  },
  {
    model: "PosCashSession",
    collection: "poscashsessions",
    domain: "POS Salón",
    purpose: "Turnos de caja: apertura, cobros agregados, conteo al cierre y varianzas.",
    fields: withTimestamps([
      { name: "sessionCode", type: "String", key: "PK lógica — código del turno.", example: "CS-…" },
      { name: "status", type: "enum", key: "open = turno abierto | closed = ya cortado" },
      { name: "shiftDate", type: "String", key: "Día operativo del turno." },
      { name: "openedByReceptionistId", type: "String", key: "FK → PosReceptionist — quien abrió." },
      { name: "openedByReceptionistName", type: "String", key: "Nombre al abrir turno." },
      { name: "closedByReceptionistId", type: "String", key: "FK → PosReceptionist — quien cerró." },
      { name: "closedByReceptionistName", type: "String", key: "Nombre al cerrar turno." },
      { name: "openingFloat", type: "Number", key: "Fondo inicial en efectivo al abrir." },
      { name: "expectedCash", type: "Number", key: "Efectivo esperado al cierre (sistema)." },
      { name: "expectedCard", type: "Number", key: "Tarjeta esperada al cierre." },
      { name: "expectedTransfer", type: "Number", key: "Transferencia esperada al cierre." },
      { name: "closingCountedCash", type: "Number", key: "Efectivo contado físicamente." },
      { name: "closingCountedCard", type: "Number", key: "Tarjeta contada / reportada." },
      { name: "closingCountedTransfer", type: "Number", key: "Transferencia contada." },
      { name: "variance", type: "Number", key: "Diferencia en efectivo (contado − esperado)." },
      { name: "cardVariance", type: "Number", key: "Diferencia en tarjeta." },
      { name: "transferVariance", type: "Number", key: "Diferencia en transferencia." },
      { name: "isPerfectCut", type: "Boolean", key: "true si todas las varianzas son cero." },
      { name: "paymentsCount", type: "Number", key: "Cantidad de cobros en el turno." },
      { name: "totalAmount", type: "Number", key: "Suma total cobrada en el turno." },
      { name: "totalEfectivo", type: "Number", key: "Total cobrado en efectivo." },
      { name: "totalTarjeta", type: "Number", key: "Total cobrado en tarjeta." },
      { name: "totalTransferencia", type: "Number", key: "Total cobrado en transferencia." },
      { name: "totalGiftCard", type: "Number", key: "Total cobrado con gift card." },
      { name: "totalGiftCardSales", type: "Number", key: "Ventas directas de gift cards en el turno." },
      { name: "closingNotes", type: "String", key: "Notas al cerrar turno." },
      { name: "closedAt", type: "Date", key: "Momento exacto del cierre." },
      { name: "openedWithMasterPin", type: "Boolean", key: "true si abrió con PIN master." },
      { name: "closedWithMasterPin", type: "Boolean", key: "true si cerró con PIN master." },
    ]),
    usedBy: ["Caja", "Corte", "Historial", "Auditoría", "Liquidaciones"],
  },
  {
    model: "PosAccountant",
    collection: "posaccountants",
    domain: "POS Salón",
    purpose: "Perfiles de contabilidad: credenciales y autorización de liquidaciones.",
    fields: withTimestamps([
      { name: "accountantCode", type: "String", key: "PK lógica — código único.", example: "CO" },
      { name: "name", type: "String", key: "Nombre mostrado en login y bitácora." },
      { name: "role", type: "String", key: "Rol (default «Contabilidad»)." },
      { name: "loginCode", type: "String", key: "PIN de 4 dígitos.", sensitive: true },
      { name: "email", type: "String", key: "Correo de contacto." },
      { name: "phone", type: "String", key: "Teléfono de contacto." },
      { name: "isActive", type: "Boolean", key: "false = perfil deshabilitado." },
    ]),
    usedBy: ["Login contadora", "Liquidaciones", "Bitácora contabilidad"],
  },
  {
    model: "PosAccountantActivity",
    collection: "posaccountantactivities",
    domain: "POS Salón",
    purpose: "Bitácora de contadora: login, logout, reportes descargados y liquidaciones.",
    fields: withTimestamps([
      { name: "activityCode", type: "String", key: "PK lógica — ej. ACT-CO-login-…" },
      { name: "accountantId", type: "String", key: "FK → PosAccountant.accountantCode" },
      { name: "accountantName", type: "String", key: "Nombre al momento del movimiento." },
      { name: "action", type: "enum", key: "login | logout | report_download | liquidation" },
      { name: "staffId", type: "String", key: "FK → PosStaff.staffCode (si aplica)" },
      { name: "staffName", type: "String", key: "Manicurista del reporte o liquidación." },
      { name: "periodMode", type: "enum", key: "day | period | vacío" },
      { name: "periodStartLabel", type: "String", key: "Inicio del periodo legible." },
      { name: "periodEndLabel", type: "String", key: "Fin del periodo legible." },
      { name: "periodStartYmd", type: "String", key: "Inicio YYYY-MM-DD." },
      { name: "periodEndYmd", type: "String", key: "Fin YYYY-MM-DD." },
      { name: "settlementCode", type: "String", key: "FK → PosStaffSettlement (liquidación)." },
      { name: "reportCode", type: "String", key: "ID del reporte descargado (ej. RPT-CA-…)." },
      {
        name: "reportSnapshot[]",
        type: "Array",
        key: "Filas congeladas: appointmentCode, date, time, clientName, serviceName, cost, commissionAmount, status",
      },
      { name: "appointmentCodes", type: "[String]", key: "FK → PosAppointment.appointmentCode" },
      { name: "paymentCodes", type: "[String]", key: "FK → PosPayment.paymentCode" },
      { name: "cashSessionCodes", type: "[String]", key: "FK → PosCashSession.sessionCode" },
      { name: "loginAuditId", type: "String", key: "FK → PosLoginAudit._id" },
      { name: "logoutReason", type: "String", key: "manual = botón salir | browser_close = cerrar pestaña" },
      { name: "isMasterSession", type: "Boolean", key: "true si entró con PIN master." },
      { name: "appointmentCount", type: "Number", key: "Citas del periodo." },
      { name: "grossAmount", type: "Number", key: "Ventas brutas del periodo." },
      { name: "paidAmount", type: "Number", key: "Comisión a pagar." },
      { name: "activityAt", type: "Date", key: "Instante del movimiento (UTC)." },
      { name: "activityDateLabel", type: "String", key: "Fecha legible en zona MX." },
      { name: "activityTimeLabel", type: "String", key: "Hora legible en zona MX." },
      { name: "metadata", type: "Mixed", key: "JSON extra opcional." },
    ]),
    usedBy: ["Equipo contadora", "Perfil manicurista", "GET /api/pos/accountant-activities"],
  },
  {
    model: "PosStaffSettlement",
    collection: "posstaffsettlements",
    domain: "POS Salón",
    purpose: "Liquidaciones de comisión pagadas a manicuristas por periodo.",
    fields: withTimestamps([
      { name: "settlementCode", type: "String", key: "PK lógica — ej. LIQ-CA-…" },
      { name: "staffId", type: "String", key: "FK → PosStaff.staffCode" },
      { name: "staffName", type: "String", key: "Nombre al liquidar." },
      { name: "periodMode", type: "enum", key: "day = un día | period = rango" },
      { name: "periodStartLabel", type: "String", key: "Inicio legible." },
      { name: "periodEndLabel", type: "String", key: "Fin legible." },
      { name: "periodStartYmd", type: "String", key: "Inicio YYYY-MM-DD — índice único con staffId." },
      { name: "periodEndYmd", type: "String", key: "Fin YYYY-MM-DD — índice único con staffId." },
      { name: "settledAt", type: "Date", key: "Instante exacto de la liquidación." },
      { name: "settledDateLabel", type: "String", key: "Día legible de liquidación." },
      { name: "grossAmount", type: "Number", key: "Ventas brutas del periodo." },
      { name: "commissionAmount", type: "Number", key: "Comisión calculada." },
      { name: "paidAmount", type: "Number", key: "Monto pagado (normalmente = commissionAmount)." },
      { name: "commissionPercent", type: "Number", key: "% usado al calcular." },
      { name: "appointmentCount", type: "Number", key: "Cantidad de citas terminadas incluidas." },
      { name: "accountantId", type: "String", key: "FK → PosAccountant.accountantCode" },
      { name: "accountantName", type: "String", key: "Nombre de contadora autorizadora." },
      { name: "notes", type: "String", key: "Notas opcionales." },
      { name: "appointmentCodes", type: "[String]", key: "FK → PosAppointment — lista de citas." },
      {
        name: "appointmentSnapshots[]",
        type: "Array",
        key: "Snapshot congelado por cita (misma estructura que reportSnapshot).",
      },
      { name: "paymentCodes", type: "[String]", key: "FK → PosPayment — cobros del periodo." },
      { name: "cashSessionCodes", type: "[String]", key: "FK → PosCashSession — turnos involucrados." },
      { name: "loginAuditId", type: "String", key: "FK → PosLoginAudit._id de autorización." },
    ]),
    usedBy: ["Perfil manicurista · Liquidar", "GET /api/pos/staff-settlements"],
  },
  {
    model: "PosLoginAudit",
    collection: "posloginaudits",
    domain: "POS Salón",
    purpose: "Auditoría: logins, liquidaciones y acciones de caja (quién, cuándo, éxito).",
    fields: withTimestamps([
      { name: "role", type: "enum", key: "reception | manicurista | accountant | master" },
      { name: "userId", type: "String", key: "Código del usuario (receptionistCode, staffCode, etc.)." },
      { name: "userName", type: "String", key: "Nombre al momento del evento." },
      { name: "success", type: "Boolean", key: "true = acción exitosa | false = falló." },
      { name: "isMaster", type: "Boolean", key: "true si usó PIN master de PosScheduleConfig." },
      { name: "action", type: "String", key: "login | staff_settlement | caja_open | caja_close | …" },
      { name: "cashSessionCode", type: "String", key: "FK → PosCashSession (acciones de caja)." },
      { name: "errorMessage", type: "String", key: "Mensaje si success = false." },
      { name: "actionDetails", type: "Mixed", key: "JSON con montos, settlementCode, etc." },
    ]),
    usedBy: ["Panel master", "Trazabilidad caja", "Liquidaciones contadora", "Login todos los roles"],
  },
  {
    model: "PosDailySnapshot",
    collection: "posdailysnapshots",
    domain: "POS Salón",
    purpose: "Resumen por fecha para la barra de agenda (contadores del día).",
    fields: withTimestamps([
      { name: "date", type: "String", key: "PK lógica — fecha del resumen." },
      { name: "citas", type: "Number", key: "Total de citas ese día." },
      { name: "sinConfirmar", type: "Number", key: "Citas aún sin confirmar." },
      { name: "pagadas", type: "Number", key: "Citas terminadas (campo legado «pagadas»)." },
      { name: "canceladas", type: "Number", key: "Citas canceladas." },
    ]),
    usedBy: ["Barra sticky de agenda"],
  },
  {
    model: "PosWeeklySnapshot",
    collection: "posweeklysnapshots",
    domain: "POS Salón",
    purpose: "KPIs semanales persistidos (sábado a viernes): citas, ventas, comisiones, propinas, neto y cortes.",
    fields: withTimestamps([
      { name: "weekStartDate", type: "String", key: "PK lógica — sábado que inicia la semana operativa." },
      { name: "weekEndDate", type: "String", key: "Viernes que cierra la semana operativa." },
      { name: "weekRangeLabel", type: "String", key: "Etiqueta legible del rango semanal." },
      { name: "completedAppointmentsCount", type: "Number", key: "Citas terminadas en la semana." },
      { name: "completedByDay", type: "Array", key: "Conteo de citas terminadas por día." },
      { name: "completedByStaff", type: "Array", key: "Conteo de citas terminadas por manicurista." },
      { name: "previousWeekCompletedCount", type: "Number", key: "Citas terminadas semana anterior." },
      { name: "completedWeekDeltaPercent", type: "Number", key: "% cambio vs semana anterior (citas)." },
      { name: "grossSales", type: "Number", key: "Venta bruta semanal (suma cost de citas terminadas)." },
      { name: "estimatedCommission", type: "Number", key: "Comisión estimada semanal." },
      { name: "tips", type: "Number", key: "Propinas semanales." },
      { name: "salonNet", type: "Number", key: "Neto salón = grossSales − estimatedCommission − tips." },
      { name: "salesByDay", type: "Array", key: "Ventas y comisión por día." },
      { name: "salesByStaff", type: "Array", key: "Ventas y comisión por manicurista." },
      { name: "previousWeekGrossSales", type: "Number", key: "Venta bruta semana anterior." },
      { name: "grossSalesWeekDeltaPercent", type: "Number", key: "% cambio vs semana anterior (ventas)." },
      { name: "cutsCount", type: "Number", key: "Cantidad de cortes cerrados en la semana." },
      { name: "cutsTotal", type: "Number", key: "Total cobrado en cortes de la semana." },
      { name: "cutsTotalEfectivo", type: "Number", key: "Efectivo en cortes semanales." },
      { name: "cutsTotalTarjeta", type: "Number", key: "Tarjeta en cortes semanales." },
      { name: "cutsTotalTransferencia", type: "Number", key: "Transferencia en cortes semanales." },
      { name: "cutsByTurn", type: "Array", key: "Detalle de cada corte del turno." },
      { name: "cutsByReceptionist", type: "Array", key: "Totales de cortes por recepcionista." },
      { name: "computedAt", type: "Date", key: "Última vez que se recalcularon los KPIs." },
    ]),
    usedBy: ["Dashboard semanal", "Ventas totales", "Citas finalizadas", "Cortes de caja"],
  },
  {
    model: "PosScheduleConfig",
    collection: "posscheduleconfigs",
    domain: "POS Salón",
    purpose: "Configuración global: horario del salón, slots y PIN master.",
    fields: withTimestamps([
      { name: "configCode", type: "String", key: "PK lógica — singleton «default»." },
      { name: "startHour", type: "Number", key: "Hora de apertura agenda (ej. 9)." },
      { name: "endHour", type: "Number", key: "Hora de cierre agenda (ej. 21)." },
      { name: "slotIntervalMinutes", type: "Number", key: "Intervalo entre slots (ej. 30 min)." },
      { name: "bookingDurationOptions", type: "[Number]", key: "Duraciones permitidas al agendar." },
      { name: "closeDurationOptions", type: "[Number]", key: "Duraciones permitidas al bloquear." },
      { name: "closeReasons", type: "[String]", key: "Motivos predefinidos de bloqueo." },
      { name: "timeZone", type: "String", key: "Zona horaria operativa (America/Mexico_City)." },
      { name: "masterLoginCode", type: "String", key: "PIN master de respaldo.", sensitive: true },
    ]),
    usedBy: ["Agenda", "Login master", "Validación PIN admin y contadora"],
  },
  {
    model: "PosExpenseCategory",
    collection: "posexpensecategories",
    domain: "POS Administración",
    purpose: "Catálogo de categorías de gasto con permisos por rol (recepción vs contadora).",
    fields: withTimestamps([
      { name: "categoryCode", type: "String", key: "PK lógica — código único.", example: "INSUMOS" },
      { name: "name", type: "String", key: "Nombre visible en formulario de gastos." },
      { name: "description", type: "String", key: "Ayuda contextual para el usuario." },
      { name: "allowedRoles", type: "enum", key: "reception | accountant | both — quién puede usar la categoría." },
      { name: "isActive", type: "Boolean", key: "false = oculta en UI." },
    ]),
    usedBy: ["Administración · Gastos", "API /pos/expense-categories"],
  },
  {
    model: "PosExpense",
    collection: "posexpenses",
    domain: "POS Administración",
    purpose: "Egresos del negocio: insumos, servicios, renta, impuestos, caja chica.",
    fields: withTimestamps([
      { name: "expenseCode", type: "String", key: "PK lógica — folio de gasto.", example: "GAS-0001" },
      { name: "categoryCode", type: "String", key: "FK → PosExpenseCategory.categoryCode" },
      { name: "categoryName", type: "String", key: "Snapshot del nombre de categoría." },
      { name: "description", type: "String", key: "Concepto del gasto." },
      { name: "amount", type: "Number", key: "Monto en MXN." },
      { name: "expenseDate", type: "String", key: "Fecha legible del gasto." },
      { name: "paymentMethod", type: "enum", key: "efectivo | tarjeta | transferencia | cheque | gift_card" },
      { name: "status", type: "enum", key: "pendiente | pagado | cancelado" },
      { name: "supplierCode", type: "String", key: "FK opcional → PosSupplier.supplierCode" },
      { name: "supplierName", type: "String", key: "Snapshot del proveedor." },
      { name: "receiptReference", type: "String", key: "Folio o factura." },
      { name: "recordedByRole", type: "enum", key: "reception | accountant | master" },
      { name: "recordedById", type: "String", key: "ID de quien registró (recepcionista o contadora)." },
      { name: "recordedByName", type: "String", key: "Nombre de quien registró." },
      { name: "cashSessionCode", type: "String", key: "FK opcional → PosCashSession.sessionCode" },
    ]),
    usedBy: ["Administración · Gastos", "Reportes contables"],
  },
  {
    model: "PosSupplier",
    collection: "possuppliers",
    domain: "POS Administración",
    purpose: "Directorio de proveedores para compras, gastos y cuentas por pagar.",
    fields: withTimestamps([
      { name: "supplierCode", type: "String", key: "PK lógica — código único.", example: "PROV-0001" },
      { name: "name", type: "String", key: "Nombre comercial." },
      { name: "contactName", type: "String", key: "Persona de contacto." },
      { name: "phone", type: "String", key: "Teléfono." },
      { name: "email", type: "String", key: "Correo." },
      { name: "taxId", type: "String", key: "RFC del proveedor." },
      { name: "category", type: "String", key: "insumos | servicios | equipo | general" },
      { name: "paymentTerms", type: "String", key: "Condiciones de pago (ej. 15 días)." },
      { name: "isActive", type: "Boolean", key: "false = dado de baja." },
      { name: "recordedByRole", type: "enum", key: "reception | accountant | master" },
      { name: "recordedByName", type: "String", key: "Quién dio de alta el proveedor." },
    ]),
    usedBy: ["Administración · Proveedores", "Compras", "Cuentas por pagar", "Gastos"],
  },
  {
    model: "PosInventoryCategory",
    collection: "posinventorycategories",
    domain: "POS Administración",
    purpose: "Categorías de inventario (insumos, herramientas, etc.).",
    fields: withTimestamps([
      { name: "categoryCode", type: "String", key: "PK lógica — código de categoría.", example: "insumos" },
      { name: "name", type: "String", key: "Nombre visible de la categoría." },
      { name: "description", type: "String", key: "Descripción opcional." },
      { name: "sortOrder", type: "Number", key: "Orden en listados." },
      { name: "isActive", type: "Boolean", key: "false = oculta en UI." },
      { name: "recordedByRole", type: "enum", key: "reception | accountant | master" },
      { name: "recordedById", type: "String", key: "Quién registró la categoría." },
      { name: "recordedByName", type: "String", key: "Nombre de quien registró." },
    ]),
    usedBy: ["Administración · Inventario", "PosInventoryItem.categoryCode"],
  },
  {
    model: "PosInventoryItem",
    collection: "posinventoryitems",
    domain: "POS Administración",
    purpose: "Stock de insumos con mínimos, costo unitario y alertas de reorden.",
    fields: withTimestamps([
      { name: "itemCode", type: "String", key: "PK lógica — código único.", example: "INV-0001" },
      { name: "name", type: "String", key: "Nombre del artículo." },
      { name: "category", type: "String", key: "esmaltes | consumibles | herramientas | limpieza" },
      { name: "unit", type: "String", key: "Unidad: pieza, litro, caja..." },
      { name: "currentStock", type: "Number", key: "Existencia actual." },
      { name: "minStock", type: "Number", key: "Mínimo antes de alerta." },
      { name: "unitCost", type: "Number", key: "Costo unitario en MXN." },
      { name: "supplierCode", type: "String", key: "FK opcional → PosSupplier.supplierCode" },
      { name: "lastRestockedAt", type: "Date", key: "Última entrada de mercancía." },
      { name: "isActive", type: "Boolean", key: "false = artículo inactivo." },
    ]),
    usedBy: ["Administración · Inventario", "Compras (auto-actualiza stock)"],
  },
  {
    model: "PosPurchase",
    collection: "pospurchases",
    domain: "POS Administración",
    purpose: "Órdenes de compra y recepción de mercancía con líneas de detalle.",
    fields: withTimestamps([
      { name: "purchaseCode", type: "String", key: "PK lógica — folio de compra.", example: "COM-0001" },
      { name: "supplierCode", type: "String", key: "FK → PosSupplier.supplierCode" },
      { name: "supplierName", type: "String", key: "Snapshot del proveedor." },
      { name: "purchaseDate", type: "String", key: "Fecha de la compra." },
      { name: "items[]", type: "Array", key: "Líneas: itemCode, name, quantity, unitCost, subtotal." },
      { name: "subtotal", type: "Number", key: "Suma de líneas." },
      { name: "tax", type: "Number", key: "IVA u otros impuestos." },
      { name: "total", type: "Number", key: "subtotal + tax." },
      { name: "status", type: "enum", key: "borrador | recibida | cancelada" },
      { name: "paymentStatus", type: "enum", key: "pendiente | parcial | pagada" },
      { name: "recordedByRole", type: "enum", key: "reception | accountant | master" },
      { name: "recordedByName", type: "String", key: "Quién registró la compra." },
    ]),
    usedBy: ["Administración · Compras", "Inventario", "Cuentas por pagar"],
  },
  {
    model: "PosPayable",
    collection: "pospayables",
    domain: "POS Administración",
    purpose: "Cuentas por pagar a proveedores con vencimiento y estado de pago.",
    fields: withTimestamps([
      { name: "payableCode", type: "String", key: "PK lógica — folio CPP.", example: "CPP-0001" },
      { name: "supplierCode", type: "String", key: "FK → PosSupplier.supplierCode" },
      { name: "supplierName", type: "String", key: "Snapshot del proveedor." },
      { name: "concept", type: "String", key: "Concepto de la obligación." },
      { name: "amount", type: "Number", key: "Monto adeudado en MXN." },
      { name: "dueDate", type: "String", key: "Fecha de vencimiento." },
      { name: "status", type: "enum", key: "pendiente | pagada | vencida | cancelada" },
      { name: "linkedExpenseCode", type: "String", key: "FK opcional → PosExpense.expenseCode" },
      { name: "linkedPurchaseCode", type: "String", key: "FK opcional → PosPurchase.purchaseCode" },
      { name: "paidAt", type: "Date", key: "Cuándo se marcó como pagada." },
      { name: "paidAmount", type: "Number", key: "Monto pagado." },
      { name: "recordedByRole", type: "enum", key: "reception | accountant | master" },
      { name: "recordedByName", type: "String", key: "Quién registró la cuenta." },
    ]),
    usedBy: ["Administración · Cuentas por pagar", "Contabilidad"],
  },
  {
    model: "User",
    collection: "users",
    domain: "ShipFast (SaaS)",
    purpose: "Usuarios web con NextAuth, Stripe y roles de administración.",
    fields: withTimestamps([
      { name: "name", type: "String", key: "Nombre del usuario web." },
      { name: "email", type: "String", key: "Correo — login OAuth / magic link.", sensitive: true },
      { name: "image", type: "String", key: "Avatar de perfil." },
      { name: "role", type: "enum", key: "user | admin | editor | moderator" },
      { name: "customerId", type: "String", key: "FK Stripe — id empieza con cus_" },
      { name: "priceId", type: "String", key: "FK Stripe — plan activo (price_…)." },
      { name: "hasAccess", type: "Boolean", key: "Acceso al producto — actualizado por webhook Stripe." },
    ]),
    usedBy: ["Dashboard SaaS", "Webhooks Stripe", "NextAuth"],
  },
  {
    model: "Lead",
    collection: "leads",
    domain: "ShipFast (SaaS)",
    purpose: "Emails capturados desde la landing (waitlist).",
    fields: withTimestamps([
      { name: "email", type: "String", key: "PK lógica — correo del lead.", sensitive: true },
    ]),
    usedBy: ["Landing", "ButtonLead", "/api/lead"],
  },
];

export const FLOW_STEPS = [
  {
    title: "Login recepción o manicurista",
    steps: [
      "PosReceptionist.loginCode o PosStaff.loginCode se valida en /api/pos/login/verify.",
      "Si el PIN coincide con PosScheduleConfig.masterLoginCode → rol master (isMaster en PosLoginAudit).",
      "Cada intento se registra en PosLoginAudit (éxito o fallo).",
      "Al entrar recepción se abre PosCashSession si no hay turno abierto.",
    ],
  },
  {
    title: "Reserva y agenda",
    steps: [
      "Se crea PosAppointment con clientId → PosClient y staffId → PosStaff.",
      "bookedByReceptionistId y bookedOnDate enlazan a PosReceptionist (contador bookingsToday).",
      "PosBlockedSlot evita solapamientos en la columna de la manicurista.",
      "PosDailySnapshot se actualiza con contadores por date.",
      "PosWeeklySnapshot se recalcula vía libs/posWeeklyStats.js (citas, cobros, cortes).",
      "PosCashTicket conecta manicurista → caja (Por cobrar).",
    ],
  },
  {
    title: "Cobro y corte",
    steps: [
      "PosCashTicket (submitted) se cobra → PosPayment + ticket charged + PosAppointment terminado.",
      "PosPayment guarda appointmentCode, ticketCode, clientId, staffId, cashSessionCode y propina.",
      "Venta PosGiftCard → PosPayment (gift_card_sale) + saldo en PosGiftCard.",
      "Totales se agregan en PosCashSession; PosClient.lastPaidVisitDate y CRM se actualizan.",
      "Al cerrar turno: conteos, varianzas, isPerfectCut, PosLoginAudit y refresh PosWeeklySnapshot.",
    ],
  },
  {
    title: "KPIs semanales (dashboard)",
    steps: [
      "PosWeeklySnapshot.weekStartDate = sábado de la semana operativa (PK única).",
      "Agrega PosAppointment (terminado), PosPayment.tip y PosCashSession (closed) del sáb–vie.",
      "Campos clave: grossSales, estimatedCommission, tips, salonNet, cutsTotal.",
      "libs/posWeeklyStats.js recalcula en citas, cobros y cierre de caja.",
      "GET /api/pos/weekly-stats · refresh=1 (semana) · refresh=all (histórico).",
    ],
  },
  {
    title: "Contabilidad y liquidaciones",
    steps: [
      "PosAccountant valida PIN; intento en PosLoginAudit y PosAccountantActivity (login) con loginAuditId.",
      "Al liquidar: PosStaffSettlement con appointmentSnapshots y FKs a citas, pagos y caja.",
      "PosAccountantActivity (liquidation) enlaza settlementCode + mismos FKs.",
      "Reporte: reportCode + reportSnapshot en Mongo (PDF solo en navegador).",
      "Logout: manual o browser_close → PosAccountantActivity (logout).",
    ],
  },
  {
    title: "Administración PYME",
    steps: [
      "PosExpenseCategory define qué categorías puede usar recepción vs contadora.",
      "PosExpense registra egresos con FK a categoría y proveedor opcional.",
      "PosSupplier alimenta compras, gastos y PosPayable (cuentas por pagar).",
      "PosPurchase actualiza PosInventoryItem al recibir mercancía.",
      "PosPayable controla obligaciones pendientes y pagos de contabilidad.",
    ],
  },
  {
    title: "CRM de clientes (Mongo)",
    steps: [
      "PosClient almacena crmSegmentFlags (7 booleanos), crmSegmentDetails y crmSegmentsSyncedAt.",
      "libs/posClientCrmSegments.js recalcula segmentos cruzando PosClient + PosAppointment.",
      "Sincronización al cargar clientes, editar clienta, citas y cobros.",
      "Segmentos: inactivas, cita próxima, sin confirmar, nuevas, cumpleaños, alertas, reagendar.",
      "Cualquier campo nuevo en Mongo debe documentarse en mongoSchemaCatalog.js → /interno.",
    ],
  },
];

const SENSITIVE_KEYS = new Set([
  "logincode",
  "masterlogincode",
  "pin",
  "password",
  "secret",
]);

export function maskSensitiveValue(key, value) {
  if (value == null || value === "") return value;
  if (!SENSITIVE_KEYS.has(String(key).toLowerCase())) return value;
  return "••••";
}

export function maskDocument(doc) {
  if (!doc || typeof doc !== "object") return doc;

  const masked = Array.isArray(doc) ? [] : {};

  for (const [key, value] of Object.entries(doc)) {
    if (value && typeof value === "object" && !Array.isArray(value) && !(value instanceof Date)) {
      masked[key] = maskDocument(value);
    } else if (Array.isArray(value)) {
      masked[key] = value.map((item) =>
        typeof item === "object" ? maskDocument(item) : item
      );
    } else {
      masked[key] = maskSensitiveValue(key, value);
    }
  }

  return masked;
}
