export const DEFAULT_INVENTORY_ITEMS = [
  // Preparación
  {
    itemCode: "INV-0001",
    name: "Nail Dehydrator / Prep",
    category: "preparacion",
    system: "universal",
    brand: "Profesional",
    shade: "",
    unit: "ml",
    currentStock: 2,
    minStock: 1,
    unitCost: 185,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0002",
    name: "Primer Ultra Bond (sin ácido)",
    category: "preparacion",
    system: "universal",
    brand: "Profesional",
    shade: "",
    unit: "ml",
    currentStock: 4,
    minStock: 2,
    unitCost: 220,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0003",
    name: "Primer ácido",
    category: "preparacion",
    system: "acrilico",
    brand: "Profesional",
    shade: "",
    unit: "ml",
    currentStock: 2,
    minStock: 1,
    unitCost: 195,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  // Bases
  {
    itemCode: "INV-0004",
    name: "Rubber Base Clear",
    category: "bases",
    system: "gel",
    brand: "Studio Pro",
    shade: "Clear",
    unit: "ml",
    currentStock: 6,
    minStock: 3,
    unitCost: 280,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0005",
    name: "Rubber Base Milky",
    category: "bases",
    system: "gel",
    brand: "Studio Pro",
    shade: "Milky",
    unit: "ml",
    currentStock: 4,
    minStock: 2,
    unitCost: 280,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0006",
    name: "Rubber Base Nude",
    category: "bases",
    system: "gel",
    brand: "Studio Pro",
    shade: "Nude",
    unit: "ml",
    currentStock: 5,
    minStock: 2,
    unitCost: 280,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0007",
    name: "Base Coat estándar",
    category: "bases",
    system: "semi",
    brand: "Studio Pro",
    shade: "",
    unit: "ml",
    currentStock: 8,
    minStock: 4,
    unitCost: 165,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0008",
    name: "Base Constructora Strong",
    category: "bases",
    system: "gel",
    brand: "Studio Pro",
    shade: "Clear",
    unit: "ml",
    currentStock: 3,
    minStock: 2,
    unitCost: 320,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  // Geles
  {
    itemCode: "INV-0009",
    name: "Hard Gel Clear",
    category: "geles",
    system: "gel",
    brand: "Studio Pro",
    shade: "Clear",
    unit: "gr",
    currentStock: 4,
    minStock: 2,
    unitCost: 420,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0010",
    name: "Builder Gel Cover Pink",
    category: "geles",
    system: "gel",
    brand: "Studio Pro",
    shade: "Cover Pink",
    unit: "gr",
    currentStock: 3,
    minStock: 2,
    unitCost: 395,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0011",
    name: "French Builder White",
    category: "geles",
    system: "gel",
    brand: "Studio Pro",
    shade: "White",
    unit: "gr",
    currentStock: 2,
    minStock: 1,
    unitCost: 380,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  // Efectos
  {
    itemCode: "INV-0012",
    name: "Polvo Chrome Plateado",
    category: "efectos",
    system: "gel",
    brand: "Efectos Pro",
    shade: "Silver",
    unit: "gr",
    currentStock: 2,
    minStock: 1,
    unitCost: 350,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0013",
    name: "Glitter Fine Gold",
    category: "efectos",
    system: "universal",
    brand: "Efectos Pro",
    shade: "Gold",
    unit: "gr",
    currentStock: 3,
    minStock: 1,
    unitCost: 120,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0014",
    name: "Cat Eye Magnet Gel",
    category: "efectos",
    system: "gel",
    brand: "Efectos Pro",
    shade: "Aurora Green",
    unit: "ml",
    currentStock: 2,
    minStock: 1,
    unitCost: 290,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0015",
    name: "Foil Transfer Holográfico",
    category: "efectos",
    system: "universal",
    brand: "Efectos Pro",
    shade: "Holo",
    unit: "rollo",
    currentStock: 4,
    minStock: 2,
    unitCost: 85,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  // Top Coat
  {
    itemCode: "INV-0016",
    name: "Top Coat No Wipe Brillante",
    category: "top-coat",
    system: "gel",
    brand: "Studio Pro",
    shade: "",
    unit: "ml",
    currentStock: 7,
    minStock: 3,
    unitCost: 195,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0017",
    name: "Top Coat Mate",
    category: "top-coat",
    system: "gel",
    brand: "Studio Pro",
    shade: "",
    unit: "ml",
    currentStock: 3,
    minStock: 2,
    unitCost: 210,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0018",
    name: "Flex Gel Top Coat",
    category: "top-coat",
    system: "gel",
    brand: "Studio Pro",
    shade: "",
    unit: "ml",
    currentStock: 2,
    minStock: 1,
    unitCost: 245,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  // Semipermanente
  {
    itemCode: "INV-0019",
    name: "Gel Polish Rojo Clásico",
    category: "semipermanente",
    system: "semi",
    brand: "Color Line",
    shade: "Rojo #42",
    unit: "ml",
    currentStock: 6,
    minStock: 3,
    unitCost: 145,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0020",
    name: "Gel Polish Nude Rosado",
    category: "semipermanente",
    system: "semi",
    brand: "Color Line",
    shade: "Nude #18",
    unit: "ml",
    currentStock: 8,
    minStock: 4,
    unitCost: 145,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0021",
    name: "Gel Polish French Blanco",
    category: "semipermanente",
    system: "semi",
    brand: "Color Line",
    shade: "White",
    unit: "ml",
    currentStock: 5,
    minStock: 2,
    unitCost: 145,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  // Acrílico
  {
    itemCode: "INV-0022",
    name: "Polvo Acrílico Clear",
    category: "acrilico",
    system: "acrilico",
    brand: "Sculpt Pro",
    shade: "Clear",
    unit: "gr",
    currentStock: 3,
    minStock: 2,
    unitCost: 310,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0023",
    name: "Polvo Acrílico Cover Pink",
    category: "acrilico",
    system: "acrilico",
    brand: "Sculpt Pro",
    shade: "Cover Pink",
    unit: "gr",
    currentStock: 2,
    minStock: 2,
    unitCost: 325,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0024",
    name: "Polvo Acrílico White",
    category: "acrilico",
    system: "acrilico",
    brand: "Sculpt Pro",
    shade: "White",
    unit: "gr",
    currentStock: 2,
    minStock: 1,
    unitCost: 310,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  // Monómero
  {
    itemCode: "INV-0025",
    name: "Monómero Acrílico Profesional",
    category: "monomero",
    system: "acrilico",
    brand: "Sculpt Pro",
    shade: "",
    unit: "ml",
    currentStock: 3,
    minStock: 2,
    unitCost: 265,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0026",
    name: "Monómero Odorless",
    category: "monomero",
    system: "acrilico",
    brand: "Sculpt Pro",
    shade: "",
    unit: "ml",
    currentStock: 2,
    minStock: 1,
    unitCost: 295,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  // Acrygel
  {
    itemCode: "INV-0027",
    name: "Acrygel Clear",
    category: "acrygel",
    system: "acrygel",
    brand: "Poly Studio",
    shade: "Clear",
    unit: "gr",
    currentStock: 4,
    minStock: 2,
    unitCost: 340,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0028",
    name: "Acrygel Nude",
    category: "acrygel",
    system: "acrygel",
    brand: "Poly Studio",
    shade: "Nude",
    unit: "gr",
    currentStock: 3,
    minStock: 2,
    unitCost: 340,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0029",
    name: "Solución Premium Acrygel",
    category: "acrygel",
    system: "acrygel",
    brand: "Poly Studio",
    shade: "",
    unit: "ml",
    currentStock: 2,
    minStock: 1,
    unitCost: 175,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  // Consumibles
  {
    itemCode: "INV-0030",
    name: "Cleaner / Prep + Clean",
    category: "consumibles",
    system: "universal",
    brand: "Profesional",
    shade: "",
    unit: "ml",
    currentStock: 4,
    minStock: 2,
    unitCost: 95,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0031",
    name: "Acetona profesional",
    category: "consumibles",
    system: "universal",
    brand: "Profesional",
    shade: "",
    unit: "litro",
    currentStock: 6,
    minStock: 3,
    unitCost: 85,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0032",
    name: "Tips Dual System (caja)",
    category: "consumibles",
    system: "universal",
    brand: "Profesional",
    shade: "Standard",
    unit: "caja",
    currentStock: 5,
    minStock: 3,
    unitCost: 180,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0033",
    name: "Moldes PVC para esculpido",
    category: "consumibles",
    system: "acrilico",
    brand: "Profesional",
    shade: "",
    unit: "caja",
    currentStock: 2,
    minStock: 3,
    unitCost: 65,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0034",
    name: "Toallitas sin pelusa (pads)",
    category: "consumibles",
    system: "universal",
    brand: "Profesional",
    shade: "",
    unit: "caja",
    currentStock: 4,
    minStock: 2,
    unitCost: 55,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  // Herramientas
  {
    itemCode: "INV-0035",
    name: "Pincel acrílico #8",
    category: "herramientas",
    system: "acrilico",
    brand: "Kolinsky",
    shade: "",
    unit: "pieza",
    currentStock: 3,
    minStock: 2,
    unitCost: 450,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0036",
    name: "Pincel gel builder #4",
    category: "herramientas",
    system: "gel",
    brand: "Kolinsky",
    shade: "",
    unit: "pieza",
    currentStock: 4,
    minStock: 2,
    unitCost: 380,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0037",
    name: "Limas 100/180",
    category: "herramientas",
    system: "universal",
    brand: "Profesional",
    shade: "",
    unit: "pieza",
    currentStock: 20,
    minStock: 10,
    unitCost: 12,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0038",
    name: "Buffer 180/240",
    category: "herramientas",
    system: "universal",
    brand: "Profesional",
    shade: "",
    unit: "pieza",
    currentStock: 8,
    minStock: 5,
    unitCost: 18,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0039",
    name: "Pincel doble Acrygel con espátula",
    category: "herramientas",
    system: "acrygel",
    brand: "Poly Studio",
    shade: "",
    unit: "pieza",
    currentStock: 3,
    minStock: 2,
    unitCost: 220,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  // Acabados
  {
    itemCode: "INV-0040",
    name: "Aceite de cutícula",
    category: "acabados",
    system: "universal",
    brand: "Spa Care",
    shade: "Almendra",
    unit: "ml",
    currentStock: 5,
    minStock: 2,
    unitCost: 95,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
  {
    itemCode: "INV-0041",
    name: "Crema hidratante de manos",
    category: "acabados",
    system: "universal",
    brand: "Spa Care",
    shade: "",
    unit: "ml",
    currentStock: 3,
    minStock: 2,
    unitCost: 120,
    supplierCode: "PROV-0001",
    supplierName: "Distribuidora de Belleza MX",
    recordedByRole: "reception",
    recordedByName: "Sistema",
  },
];

export const DEFAULT_EXPENSE_CATEGORIES = [
  {
    categoryCode: "INSUMOS",
    name: "Insumos operativos",
    description: "Esmaltes, acetona, limas y consumibles del día a día.",
    allowedRoles: "reception",
  },
  {
    categoryCode: "CAJA_CHICA",
    name: "Caja chica",
    description: "Gastos menores pagados en efectivo desde recepción.",
    allowedRoles: "reception",
  },
  {
    categoryCode: "LIMPIEZA",
    name: "Limpieza e higiene",
    description: "Productos de limpieza y desinfección.",
    allowedRoles: "reception",
  },
  {
    categoryCode: "SERVICIOS",
    name: "Servicios (luz, agua, internet)",
    description: "Recibos de servicios públicos y telecomunicaciones.",
    allowedRoles: "accountant",
  },
  {
    categoryCode: "RENTA",
    name: "Renta",
    description: "Pago de arrendamiento del local.",
    allowedRoles: "accountant",
  },
  {
    categoryCode: "NOMINA",
    name: "Nómina y prestaciones",
    description: "Pagos de nómina, IMSS y prestaciones.",
    allowedRoles: "accountant",
  },
  {
    categoryCode: "IMPUESTOS",
    name: "Impuestos",
    description: "ISR, IVA y obligaciones fiscales.",
    allowedRoles: "accountant",
  },
  {
    categoryCode: "MANTENIMIENTO",
    name: "Mantenimiento",
    description: "Reparaciones y mantenimiento de equipo o local.",
    allowedRoles: "both",
  },
  {
    categoryCode: "MARKETING",
    name: "Marketing",
    description: "Publicidad, promociones y material gráfico.",
    allowedRoles: "accountant",
  },
  {
    categoryCode: "OTROS",
    name: "Otros gastos",
    description: "Gastos no clasificados en otra categoría.",
    allowedRoles: "both",
  },
];

export const DEFAULT_SUPPLIERS = [
  {
    supplierCode: "PROV-0001",
    name: "Distribuidora de Belleza MX",
    contactName: "Laura Méndez",
    phone: "5512345678",
    email: "ventas@bellezamx.com",
    category: "insumos",
    paymentTerms: "15 días",
    notes: "Proveedor principal de esmaltes y consumibles.",
    recordedByRole: "accountant",
    recordedByName: "Sistema",
  },
  {
    supplierCode: "PROV-0002",
    name: "Servicios Integrales del Valle",
    contactName: "Carlos Ruiz",
    phone: "5587654321",
    email: "facturacion@sivalle.com",
    category: "servicios",
    paymentTerms: "Contado",
    notes: "Mantenimiento y limpieza profunda.",
    recordedByRole: "accountant",
    recordedByName: "Sistema",
  },
];

import PosExpenseCategory from "@/models/PosExpenseCategory";
import PosSupplier from "@/models/PosSupplier";
import PosInventoryItem from "@/models/PosInventoryItem";

export async function seedPosExpenseCategoriesIfEmpty() {
  const count = await PosExpenseCategory.countDocuments();
  if (count > 0) return false;

  await PosExpenseCategory.insertMany(DEFAULT_EXPENSE_CATEGORIES);
  return true;
}

export async function seedPosSuppliersIfEmpty() {
  const count = await PosSupplier.countDocuments();
  if (count > 0) return false;

  await PosSupplier.insertMany(DEFAULT_SUPPLIERS);
  return true;
}

export async function seedPosInventoryIfEmpty() {
  const count = await PosInventoryItem.countDocuments();
  if (count > 0) return false;

  await PosInventoryItem.insertMany(DEFAULT_INVENTORY_ITEMS);
  return true;
}

export async function seedPosAdminIfEmpty() {
  await seedPosExpenseCategoriesIfEmpty();
  await seedPosSuppliersIfEmpty();
  await seedPosInventoryIfEmpty();
}

